// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd.proto

// https://blog.csdn.net/u011518120/article/details/54604615
// protoc --go_out=. cmd.proto

package http2proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cmd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ArgInfo              []byte   `protobuf:"bytes,2,opt,name=argInfo,proto3" json:"argInfo,omitempty"`
	ResInfo              []byte   `protobuf:"bytes,3,opt,name=resInfo,proto3" json:"resInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cmd) Reset()         { *m = Cmd{} }
func (m *Cmd) String() string { return proto.CompactTextString(m) }
func (*Cmd) ProtoMessage()    {}
func (*Cmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{0}
}

func (m *Cmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cmd.Unmarshal(m, b)
}
func (m *Cmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cmd.Marshal(b, m, deterministic)
}
func (m *Cmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cmd.Merge(m, src)
}
func (m *Cmd) XXX_Size() int {
	return xxx_messageInfo_Cmd.Size(m)
}
func (m *Cmd) XXX_DiscardUnknown() {
	xxx_messageInfo_Cmd.DiscardUnknown(m)
}

var xxx_messageInfo_Cmd proto.InternalMessageInfo

func (m *Cmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cmd) GetArgInfo() []byte {
	if m != nil {
		return m.ArgInfo
	}
	return nil
}

func (m *Cmd) GetResInfo() []byte {
	if m != nil {
		return m.ResInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*Cmd)(nil), "http2proto.cmd")
}

func init() { proto.RegisterFile("cmd.proto", fileDescriptor_7520252fb01eaf30) }

var fileDescriptor_7520252fb01eaf30 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xce, 0x4d, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xca, 0x28, 0x29, 0x29, 0x30, 0x02, 0xb3, 0x95, 0x7c,
	0xb9, 0x98, 0x93, 0x73, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xc4, 0xa2, 0x74, 0xcf, 0xbc, 0xb4,
	0x7c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x18, 0x17, 0x24, 0x53, 0x94, 0x5a, 0x0c, 0x96,
	0x61, 0x86, 0xc8, 0x40, 0xb9, 0x49, 0x6c, 0x60, 0x53, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x74, 0xea, 0x39, 0x66, 0x6e, 0x00, 0x00, 0x00,
}
